# frozen_string_literal: true
# Auto-set og:image for each post based on its slug.
# Assets/og/<slug>.png must be pre-generated by scripts/generate-og-images.py
# before jekyll build. jekyll-seo-tag picks up post.data['image'] automatically.

Jekyll::Hooks.register :posts, :post_init do |post|
  slug = post.data["slug"] || post.basename.gsub(/^\d{4}-\d{2}-\d{2}-/, "").gsub(/\.md$/, "")
  og_path = "/assets/og/#{slug}.png"
  post.data["image"] ||= og_path
end
